# herta titles
titles = ["'Home-Use Object Finder' After-Sales Feedback Form",
"(Recording) A Fool's Play: Calamity's Wrath Seeks Olden Clash, Fool's Blade Rends Divine Flesh",
"Adler's Research Report on Ghost Stories",
"An Incomplete Automatic Transcript",
"Arlan's Work Log",
"Asta and Business Elite Correspondence Records",
"Asta's Equipment Purchase Contract",
"Asta's Letters From Home",
"Asta's Shopping List",
"Attack Records of the Obstacle Detection Terminal",
"Bye, Herta",
"Chat History Between Researchers",
"Comet Hunter's Treasure",
"Confession Letter",
"Curio Management Log",
"Feedback Form for the Space Station Staff Cafeteria",
"Fragment of a Weekly Report by a Department of Ecology Researcher",
"Fragments of Herta Research Atlas Volume 7: Traffic",
"Galaxy Public Service Award",
"Herta Asset Damage Evaluation",
"Herta Collection Room Code of Conduct",
"Herta's Manuscripts",
"Kapo-Kali Secret Recipe",
"Letter From Locus Silentii",
"Letter From the Comet Hunter",
"Notification for Physical Examinations",
"Observation on Wubbaboo Behavior",
"Research Report: Tottonid Crystals",
"Researcher Eikura Shuu's Diary",
"Researchers' Memo Notes",
"Sheila's Character Script",
"Space Station Introductory Guide",
"Space Station Love Poems",
"Species of the Galaxy: Tottonid",
"Species of the Galaxy: Wubbaboo",
"The Curlcademy Guidelines",
"The Well-Kept Secret of the Maintenance Department",
"Tottonids Are Rocks",
"Update Notes for Master Capote's Life Wiki Version 12.0",
"Xin-41 Homeward Cloud Messaging]"]

# images for herta
formats = ["/images/itemElectronicNotice.webp",
"/readables/A Fool's Play.png",
"/images/itemJournal.webp",
"/readables/An Incomplete Automatic Transcript.png",
"/images/itemJournal.webp",
"/readables/AstaOffice.png",
"itemJournalPage.jpeg",
"/readables/AstaOffice.png",
"/readables/AstaOffice.png",
"/readables/AttackRecordsKapoKali.png",
"/readables/ByeHertaLoveLetter.png",
"/readables/LetterCometChatHis.png",
"/images/itemJournalPage.jpeg",
"/readables/Confession.png",
"/readables/CurioManagement.png",
"/readables/Feedback.png",
"/readables/ReportByEco.png",
"/readables/V7Traffic.png",
"/readables/PublicAward.png",
"/images/itemJournalPage.jpeg",
"/readables/CodeConduct.png",
"/readables/HertaManu.png",
"/readables/AttackRecordsKapoKali.png",
"/images/itemJournal.webp",
"/readables/LetterCometChatHis.png",
"/readables/PhysEx.png",
"/images/itemJournal.webp",
"/readables/RRTottnid.png",
"/images/itemJournal.webp",
"/readables/Memo1-6.png",
"/readables/Sheila.png",
"/readables/ManuPrefaceIntroGuide.png",
"/readables/ByeHertaLoveLetter.png",
"/readables/SpeciesTott.png",
"/readables/SpeciesWubb.png",
"/images/itemJournal.webp",
"/readables/KeptSecret.png",
"readables/TottRocks.png",
"/images/itemJournal.webp",
"/images/itemJournal.webp"]

# jarilo VI (unfinished)
jariloImages = [
    'https://i.imgur.com/W5ECVcT.jpeg', 
    'https://i.imgur.com/KXJouoD.jpeg', 
    'https://i.imgur.com/hrzkpj1.jpeg', 
    'https://i.imgur.com/xWNHlwF.jpeg', 
    'https://i.imgur.com/0Hq5kyU.jpeg', 
    'https://i.imgur.com/LnHGaV1.jpeg', 
    'https://i.imgur.com/uZHG35T.jpeg', 
    'https://i.imgur.com/8rYfIe0.jpeg', 
    'https://i.imgur.com/BzdpVUD.jpeg', 
    'https://i.imgur.com/g2Dgp0g.jpeg', 
    'https://i.imgur.com/dFPuSdf.jpeg', 
    'https://i.imgur.com/mILoBQ1.jpeg', 
    'https://i.imgur.com/NGUZIzp.jpeg', 
    'https://i.imgur.com/vMUpKvp.jpeg', 
    'https://i.imgur.com/0VGk5Lb.jpeg', 
    'https://i.imgur.com/OW00RoR.jpeg', 
    'https://i.imgur.com/QFC56qX.jpeg', 
    'https://i.imgur.com/0VGk5Lb.jpeg', 
    'https://i.imgur.com/OW00RoR.jpeg', 
    'https://i.imgur.com/rVEep1B.jpeg', 
    'https://i.imgur.com/dV9Mltl.jpeg', 
    'https://i.imgur.com/VFcGEwu.jpeg', 
    'https://i.imgur.com/0VGk5Lb.jpeg', 
    'https://i.imgur.com/0VGk5Lb.jpeg', 
    'https://i.imgur.com/OW00RoR.jpeg', 
    'https://i.imgur.com/OW00RoR.jpeg', 
    'https://i.imgur.com/OW00RoR.jpeg', 
    'https://i.imgur.com/OW00RoR.jpeg', 
    'https://i.imgur.com/OW00RoR.jpeg'
    ]

jariloTitles = [
    "Floriography Manual Attached to a Bouquet",
    "Remnants of a Barista's Handbook",
    "Miner's Safety Manual",
    "Solwarm Festival Celebration Plans",
    "Mining Equipment Order List",
    "Tempering Workshop: A Fresh Start!",
    "Notice Under Bridge",
    "Family Secret: Spicy Puffy Mushrooms",
    "Great Mine Shift Board",
    "Miners Weekly",
    "Wildfire Flier",
    "Miners' Ultimatum",
    "Great Mine Code of Conduct",
    "Customer Notice From Balaway the Miner's Lamp",
    "Ice Storm Causes",
    "Jarilo: God of Spring and War",
    "Message For New Repairers",
    "Interview on Daily Life Before the Solwarm Festival",
    "Fashion Brand 'Suburbia'",
    "Mine Poison Antidote Inhalant Manual",
    "Diary of a Civilian Scientist",
    "A Letter Pieced Together",
    "Snapper Jam Appetizer",
    "The Traveler Who Survived the Blizzard",
    "Oratorio 'Supreme Guardian' Premiere Spectacular",
    "Rye Bread Soda Iceberg",
    "Bellerain Petroleum Jelly",
    "Dreamland Analysis",
    "Time Change Notice For Oratorio Rehearsal",
    "Belobog Sausage",
    "A Child's Letter",
    "Underground Encyclopedia: Plants and Fungi",
    "Recipe: Crystal Lizard Satay",
    "The Seven Wonders of Belobog",
    "The Adventurous Moles: Hidden Treasure",
    "Tale of the Winterlands",
    "Letter attached to a package",
    "Pet Diary: Sesame",
    "Underground Encyclopedia: Animals",
    "Miner's Lamp Ancient Relic Appraisal Record",
    "Miner's Medical Certificate",
    "Maddon Tunnel Is Collapsing",
    "Vache's Letter",
    "Blizzard Immunity Lab Records",
    "A Good Establishment Births Generations of Wealth",
    "Mining Equipment Purchase Order",
    "Request for Provisions",
    "Fragmented Diary",
    "Notice: Additional Barricades on the Main Road of the Plaza",
    "Greasy Food Magazine",
    "Venerable Guards Will Defend Us From Enemies!",
    "Dreamchaser's Letter",
    "Opening of the New Tempering Workshop!",
    "Observation Diary of a 'Changed' Child",
    "Military Machinery Routine Maintenance Record Form",
    "Rap Battle Voting Channel Opens",
    "Will Bite, Do Not Approach!",
    "Boxer Recruitment Form",
    "Musicians of Belobog",
    "Unsent Letter",
    "Goethe Hotel Tea Time Menu",
    "Gathering Place Message Board",
    "A Letter to All of Furnace Core Base",
    "Old Newspapers of Backwater Pass",
    "Evening Ember at the Goethe Hotel",
    "Once Upon a Snowsieged Country Program",
    "Leisha and Mrs. Trude Program",
    "Roadside Picnic Program",
    "Beneath the White Cloak Program",
    "Clara Protection Society Is Seeking New Members!",
    "Natasha's List",
    "Densely Packed Schedule",
    "Report on Recent Activities in the Silvermane Guard Restricted Zone and Related Suggestions",
    "Crystal Daily's Sample Article for the Censorship Office",
    "Journey of the Moles - Belobog Ancient Poetry Collection",
    "Belobog Academy's Mid-Term Exam Paper",
    "Anti-Fraud Guide, Edited Version",
    "Looking for a Friend",
    "Oath of the Silvermane Guards",
    "Pascal's Diary",
    "A Call From The Fragmentum",
    "Cyrille",
    "Belobog Chronicles: Before the Eternal Freeze",
    "Wanted Poster Gallery"
]

xianTitles = [
    "An Evening Journey Through Exalting Sanctum",
    "Starskiff Safety Inspection Guide",
    "Management Strategy for Reporting Starskiff Traffic",
    "The startaro bubble tea tastes horrible.",
    "Return to the Future",
    "A Drizzle Douses Dust",
    "100 Common Xianzhou Proverbs for Outworlders - On Travel: Arriving at the Xianzhou",
    "100 Common Xianzhou Proverbs for Outworlders - On Travel: Presenting Gifts",
    "100 Common Xianzhou Proverbs for Outworlders - On Work: Life in the Workplace",
    "An Unsuitable Job for A Puppet",
    "Protecting Starskiff Haven - Part I",
    "Protecting Starskiff Haven - Part II",
    "Protecting Starskiff Haven - Part III",
    "Travelogue on Xianzhou - Delves ",
    "Travelogue on Xianzhou - Starskiff",
    "Travelogue on Xianzhou - Realm-Keeping Commission",
    "Travelogue on Xianzhou - Artisanship Commission",
    "Travelogue on Xianzhou - Jade Abacus",
    "Travelogue on Xianzhou - Long-life Species I",
    "Travelogue on Xianzhou - Long-Life Species, Part 2",
    "Cloud Knights Against the Borisin",
    "Amnesic Meditation Therapy: A Guide to A Long, Healthy Life!",
    "Codex of Apocrypha",
    "Annotations from 'Ode to Reignbow Path'",
    "General's Diary",
    "Butterfly Shadow's Special Issue: The Ten Best Butterfly Immersias of the Millennium - No. 1 through 9",
    "Butterfly Shadow's Special Issue: The Ten Best Butterfly Immersias of the Millennium - No. 10: Robe Brethren",
    "The Luofu Sky-Faring Commission Guilds List",
    "Tiger Boxing Gym Admissions Ad",
    "Advocate legal and reasonable care for animals, strictly prohibit illegal wildlife trade for 'releases'",
    "History of the Xianzhou: Errata - History of the Xianzhou: Three Sufferings - Fragmented Vol. 1",
    "History of the Xianzhou: Errata - History of the Xianzhou: Three Sufferings - Fragmented Vol. 2",
    "History of the Xianzhou: Errata - Summary of the Chronicles of the Sky-Faring Commission: 3287 Star Calendar - Vol. 3",
    "History of the Xianzhou: Errata - Xianzhou Alliance Declaration: A Preface (Digital Rubbing)",
    "Cloudcry Songbook",
    "Surveillance Report from the Xianzhou Yuque",
    "List of Archenemies",
    "Dahao's Diary",
    "Record of Reignbow's Road",
    "Divination Report",
    "Glimpses into the Beyond - 'Inquiry Into The Gods: An Introduction'",
    "Glimpses into the Beyond - 'Inquiry Into The Gods: The Arbiters'",
    "Glimpses into the Beyond - 'Inquiry Into The Gods: The Sacrosancts'",
    "Glimpses into the Beyond - 'Inquiry Into The Gods: The Authors of Calamity'",
    "Records of Yellowbell Resonance",
    "Records of the Early Nation (Fragment)",
    "A Martial Arts Novel That Stopped Updating 300 Years Ago",
    "A Collection of Intelligence on the Xianzhou Luofu",
    "Dan Shu's Diary (I)",
    "Dan Shu's Diary (II)",
    "Overview of Xianzhou's Materia Medica - The Medical Research Collection",
    "Overview of Xianzhou's Materia Medica - The Unorthodox Collection",
    "Overview of Xianzhou's Materia Medica - The Heretical Collection",
    "Compendium of Remedies",
    "Official Announcement on the Origins of the Disciples of Sanctus Medicus",
    "An Exchange Diary Between Pilots",
    "A Page From the Alchemy Commission's Official Gazette",
    "Selected Classic Case Studies",
    "Undestroyed Letter",
    "Undestroyed Notes",
    "Report: A Rare Plant Specimen",
    "Zhongshan's Letter",
    "Verdict: The Great Rebellion of Lunae",
    "The Account of Preceptor Sutuan Crafting a Statue of the High Elder",
    "Artisan Congyan's Stone Engraving",
    "The Pearlkeeper's Communication Stele",
    "Shredded Notes of Scholar Bernini",
    "Vidyadhara Elegy: Insight on 'Six Charioteers Adjudicating the Imbibitor Lunae'",
    "A Vidyadhara Youth's Notes",
    "Preceptor Assembly Chronicle Fragment",
    "Investigation of Ancient Pattern Rubbings from the Luofu",
    "Observational Monument on the Roots of the Arbor",
    "Disciples of Sanctus Medicus: Collection of Exhibits"
]

xianFormats = ['https://i.imgur.com/bWCKlBC.jpeg', 'https://i.imgur.com/9PGGr1Q.jpeg', 'https://i.imgur.com/ToweIBj.jpeg', 'https://i.imgur.com/hJaJqLV.jpeg', 'https://i.imgur.com/T3PJHFY.jpeg', 'https://i.imgur.com/1bRNayt.jpeg', 'https://i.imgur.com/o72UFlL.jpeg', 'https://i.imgur.com/yMdYssf.jpeg', 'https://i.imgur.com/yMdYssf.jpeg', 'https://i.imgur.com/kZ7nYdg.jpeg', 'https://i.imgur.com/8gBTimg.jpeg', 'https://i.imgur.com/8gBTimg.jpeg', 'https://i.imgur.com/8gBTimg.jpeg', 'https://i.imgur.com/cZ8I97O.jpeg', 'https://i.imgur.com/ZfPrrNO.jpeg', 'https://i.imgur.com/aZG5ssX.jpeg', 'https://i.imgur.com/fF5O2c5.jpeg', 'https://i.imgur.com/W64cN1f.jpeg', 'https://i.imgur.com/am7GVLi.jpeg', 'https://i.imgur.com/eMXSSfU.jpeg', 'https://i.imgur.com/zsvcQ7e.jpeg', 'https://i.imgur.com/DqSF0UJ.jpeg', 'https://i.imgur.com/kZ7nYdg.jpeg', 'https://i.imgur.com/kZ7nYdg.jpeg', 'https://i.imgur.com/JRMIlKC.jpeg', 'https://i.imgur.com/kZ7nYdg.jpeg', 'https://i.imgur.com/iqUKxXR.jpeg', 'https://i.imgur.com/yMdYssf.jpeg', 'https://i.imgur.com/0uhW9BK.jpeg', 'https://i.imgur.com/1LFY03d.jpeg', 'https://i.imgur.com/7o71vaF.jpeg', 'https://i.imgur.com/MfCrKH8.jpeg', 'https://i.imgur.com/yMdYssf.jpeg', 'https://i.imgur.com/JRMIlKC.jpeg', 'https://i.imgur.com/tVMZfsE.jpeg', 'https://i.imgur.com/JRMIlKC.jpeg', 'https://i.imgur.com/JRMIlKC.jpeg', 'https://i.imgur.com/bL3a2Yy.jpeg', 'https://i.imgur.com/8gBTimg.jpeg', 'https://i.imgur.com/5EcezA2.jpeg', 'https://i.imgur.com/vFQwRLr.jpeg', 'https://i.imgur.com/NpBt9CD.jpeg', 'https://i.imgur.com/tNtqEFd.jpeg', 'https://i.imgur.com/SWSt80J.jpeg', 'https://i.imgur.com/9mtHH4n.jpeg', 'https://i.imgur.com/yMdYssf.jpeg', 'https://i.imgur.com/8fsLTnj.jpeg', 'https://i.imgur.com/kZ7nYdg.jpeg', 'https://i.imgur.com/StxQr4R.jpeg', 'https://i.imgur.com/8Yew7Ul.jpeg', 'https://i.imgur.com/dWIEh5c.jpeg', 'https://i.imgur.com/EEeUGi5.jpeg', 'https://i.imgur.com/7kOCRIB.jpeg', 'https://i.imgur.com/SbooFQw.jpeg', 'https://i.imgur.com/dI1oQBq.jpeg', 'https://i.imgur.com/Z1qFpFc.jpeg', 'https://i.imgur.com/qFc25SI.jpeg', 'https://i.imgur.com/6TyZjh0.jpeg', 'https://i.imgur.com/LI6a1EY.jpeg', 'https://i.imgur.com/Jy7Lxgc.jpeg', 'https://i.imgur.com/dI1oQBq.jpeg', 'https://i.imgur.com/uYoDhWr.jpeg', 'https://i.imgur.com/H2RGhfS.jpeg', 'https://i.imgur.com/ydGhqeh.jpeg', 'https://i.imgur.com/dqmY47c.jpeg', 'https://i.imgur.com/obdXTAc.jpeg', 'https://i.imgur.com/dI1oQBq.jpeg', 'https://i.imgur.com/J0Zcj3C.jpeg', 'https://i.imgur.com/QRTS3aw.jpeg', 'https://i.imgur.com/edAsIht.jpeg', 'https://i.imgur.com/dI1oQBq.jpeg', 'https://i.imgur.com/RVZYqkJ.jpeg', "images/xianParchment.webp"]

def main(titles, formats):
    x = 0
    for title in titles:
        if x%3 ==0:
            print('<div class="w3-row-padding">')
        format = formats[x]
        print(f'<div class="w3-third w3-container w3-margin-bottom">\n<img class="myImages w3-hover-opacity" id="myImg" src="{format}" alt="{title}" style="width:100%">\n<div class="w3-container w3-white">\n<p><b>{title}</b></p>\n</div>\n</div>')
        if x%3 ==2:
            print('</div>')
        x+=1
    

main(xianTitles, xianFormats)
print('<div id="defaultModal" class="modal">\n<span class="close">&times;</span>\n<img class="modal-content" id="img01">\n<div id="caption">Location</div>\n</div>')