titles = ["'Home-Use Object Finder' After-Sales Feedback Form",
"(Recording) A Fool's Play: Calamity's Wrath Seeks Olden Clash, Fool's Blade Rends Divine Flesh",
"Adler's Research Report on Ghost Stories",
"An Incomplete Automatic Transcript",
"Arlan's Work Log",
"Asta and Business Elite Correspondence Records",
"Asta's Equipment Purchase Contract",
"Asta's Letters From Home",
"Asta's Shopping List",
"Attack Records of the Obstacle Detection Terminal",
"Bye, Herta",
"Chat History Between Researchers",
"Comet Hunter's Treasure",
"Confession Letter",
"Curio Management Log",
"Feedback Form for the Space Station Staff Cafeteria",
"Fragment of a Weekly Report by a Department of Ecology Researcher",
"Fragments of Herta Research Atlas Volume 7: Traffic",
"Galaxy Public Service Award",
"Herta Asset Damage Evaluation",
"Herta Collection Room Code of Conduct",
"Herta's Manuscripts",
"Kapo-Kali Secret Recipe",
"Letter From Locus Silentii",
"Letter From the Comet Hunter",
"Notification for Physical Examinations",
"Observation on Wubbaboo Behavior",
"Research Report: Tottonid Crystals",
"Researcher Eikura Shuu's Diary",
"Researchers' Memo Notes",
"Sheila's Character Script",
"Space Station Introductory Guide",
"Space Station Love Poems",
"Species of the Galaxy: Tottonid",
"Species of the Galaxy: Wubbaboo",
"The Curlcademy Guidelines",
"The Well-Kept Secret of the Maintenance Department",
"Tottonids Are Rocks",
"Update Notes for Master Capote's Life Wiki Version 12.0",
"Xin-41 Homeward Cloud Messaging]"]

formats = ["itemElectronicNotice.webp",
"itemJournal.webp",
"itemJournal.webp",
"itemJournalPage.jpeg",
"itemJournal.webp",
"itemJournalPage.jpeg",
"itemJournalPage.jpeg",
"itemElectronicNotice.webp",
"itemJournalPage.jpeg",
"itemJournal.webp",
"itemJournal.webp",
"itemJournal.webp",
"itemJournalPage.jpeg",
"itemJournal.webp",
"itemJournal.webp",
"itemJournal.webp",
"itemJournal.webp",
"itemJournalPage.jpeg",
"itemJournal.webp",
"itemJournalPage.jpeg",
"itemJournal.webp",
"itemJournal.webp",
"itemJournalPage.jpeg",
"itemJournal.webp",
"itemElectronicNotice.webp",
"itemJournal.webp",
"itemJournal.webp",
"itemJournal.webp",
"itemJournal.webp",
"itemJournalPage.jpeg",
"itemJournal.webp",
"itemJournal.webp",
"itemJournal.webp",
"itemJournal.webp",
"itemJournal.webp",
"itemJournal.webp",
"itemJournal.webp",
"itemJournal.webp",
"itemJournal.webp",
"itemJournal.webp"]

def main(titles, formats):
    x = 0
    print('<div class="w3-row-padding">')
    for title in titles:
        format = formats[x]
        print(f'<div class="w3-third w3-container w3-margin-bottom">\n<img src="/images/{format}" alt="{title}" style="width:100%" class="w3-hover-opacity">\n<div class="w3-container w3-white">\n<p><b>{title}</b></p>\n</div>\n</div>')
        x+=1
main(titles, formats)