images = xianFormats = [
    '=image("https://i.imgur.com/bWCKlBC.jpeg")',
    '=image("https://i.imgur.com/9PGGr1Q.jpeg")',
    '=image("https://i.imgur.com/ToweIBj.jpeg")',
    '=image("https://i.imgur.com/hJaJqLV.jpeg")',
    '=image("https://i.imgur.com/T3PJHFY.jpeg")',
    '=image("https://i.imgur.com/1bRNayt.jpeg")',
    '=image("https://i.imgur.com/o72UFlL.jpeg")',
    '=image("https://i.imgur.com/yMdYssf.jpeg")',
    '=image("https://i.imgur.com/yMdYssf.jpeg")',
    '=image("https://i.imgur.com/kZ7nYdg.jpeg")',
    '=image("https://i.imgur.com/8gBTimg.jpeg")',
    '=image("https://i.imgur.com/8gBTimg.jpeg")',
    '=image("https://i.imgur.com/8gBTimg.jpeg")',
    '=image("https://i.imgur.com/cZ8I97O.jpeg")',
    '=image("https://i.imgur.com/ZfPrrNO.jpeg")',
    '=image("https://i.imgur.com/aZG5ssX.jpeg")',
    '=image("https://i.imgur.com/fF5O2c5.jpeg")',
    '=image("https://i.imgur.com/W64cN1f.jpeg")',
    '=image("https://i.imgur.com/am7GVLi.jpeg")',
    '=image("https://i.imgur.com/eMXSSfU.jpeg")',
    '=image("https://i.imgur.com/zsvcQ7e.jpeg")',
    '=image("https://i.imgur.com/DqSF0UJ.jpeg")',
    '=image("https://i.imgur.com/kZ7nYdg.jpeg")',
    '=image("https://i.imgur.com/kZ7nYdg.jpeg")',
    '=image("https://i.imgur.com/JRMIlKC.jpeg")',
    '=image("https://i.imgur.com/kZ7nYdg.jpeg")',
    '=image("https://i.imgur.com/iqUKxXR.jpeg")',
    '=image("https://i.imgur.com/yMdYssf.jpeg")',
    '=image("https://i.imgur.com/0uhW9BK.jpeg")',
    '=image("https://i.imgur.com/1LFY03d.jpeg")',
    '=image("https://i.imgur.com/7o71vaF.jpeg")',
    '=image("https://i.imgur.com/MfCrKH8.jpeg")',
    '=image("https://i.imgur.com/yMdYssf.jpeg")',
    '=image("https://i.imgur.com/JRMIlKC.jpeg")',
    '=image("https://i.imgur.com/tVMZfsE.jpeg")',
    '=image("https://i.imgur.com/JRMIlKC.jpeg")',
    '=image("https://i.imgur.com/JRMIlKC.jpeg")',
    '=image("https://i.imgur.com/bL3a2Yy.jpeg")',
    '=image("https://i.imgur.com/8gBTimg.jpeg")',
    '=image("https://i.imgur.com/5EcezA2.jpeg")',
    '=image("https://i.imgur.com/vFQwRLr.jpeg")',
    '=image("https://i.imgur.com/NpBt9CD.jpeg")',
    '=image("https://i.imgur.com/tNtqEFd.jpeg")',
    '=image("https://i.imgur.com/SWSt80J.jpeg")',
    '=image("https://i.imgur.com/9mtHH4n.jpeg")',
    '=image("https://i.imgur.com/yMdYssf.jpeg")',
    '=image("https://i.imgur.com/8fsLTnj.jpeg")',
    '=image("https://i.imgur.com/kZ7nYdg.jpeg")',
    '=image("https://i.imgur.com/StxQr4R.jpeg")',
    '=image("https://i.imgur.com/8Yew7Ul.jpeg")',
    '=image("https://i.imgur.com/dWIEh5c.jpeg")',
    '=image("https://i.imgur.com/EEeUGi5.jpeg")',
    '=image("https://i.imgur.com/7kOCRIB.jpeg")',
    '=image("https://i.imgur.com/SbooFQw.jpeg")',
    '=image("https://i.imgur.com/dI1oQBq.jpeg")',
    '=image("https://i.imgur.com/Z1qFpFc.jpeg")',
    '=image("https://i.imgur.com/qFc25SI.jpeg")',
    '=image("https://i.imgur.com/6TyZjh0.jpeg")',
    '=image("https://i.imgur.com/LI6a1EY.jpeg")',
    '=image("https://i.imgur.com/Jy7Lxgc.jpeg")',
    '=image("https://i.imgur.com/dI1oQBq.jpeg")',
    '=image("https://i.imgur.com/uYoDhWr.jpeg")',
    '=image("https://i.imgur.com/H2RGhfS.jpeg")',
    '=image("https://i.imgur.com/ydGhqeh.jpeg")',
    '=image("https://i.imgur.com/dqmY47c.jpeg")',
    '=image("https://i.imgur.com/obdXTAc.jpeg")',
    '=image("https://i.imgur.com/dI1oQBq.jpeg")',
    '=image("https://i.imgur.com/J0Zcj3C.jpeg")',
    '=image("https://i.imgur.com/QRTS3aw.jpeg")',
    '=image("https://i.imgur.com/edAsIht.jpeg")',
    '=image("https://i.imgur.com/dI1oQBq.jpeg")',
    '=image("https://i.imgur.com/RVZYqkJ.jpeg")'
]

data = []

for image in images:
    if "=image" in image:
        substring = image[8:-2]
        data.append(substring)

print(data)

